<a href="https://colab.research.google.com/github/DiegoRodrigues1402/Cadastro-Python/blob/main/lista_frutas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import requests
import json
import pandas as pd

In [2]:
dados_frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [7]:
resultado = json.loads(dados_frutas.text)

In [10]:
dados = pd.DataFrame(resultado)
dados.head(10)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."

In [27]:
pd.json_normalize(dados['nutritions'])

    calories    fat  sugar  carbohydrates  protein
0         81   0.00  18.00          18.00     0.00
1         29   0.40   5.40           5.50     0.80
2         96   0.20  17.20          22.00     1.00
3         74   0.20   2.60           3.90     0.90
4         57   0.10  10.00          15.00     0.40
5        147   5.30   6.75          27.10     1.50
6         40   0.40   4.50           9.00     1.30
7         50   0.34   5.74          11.30     0.75
8         61   0.50   9.00          15.00     1.10
9         66   0.44  15.00          17.00     0.80
10        50   0.12   9.85          13.12     0.54
11        74   0.30  16.00          19.00     0.80
12        44   0.60   0.00          10.00     0.90
13        97   0.70  11.20          22.40     2.20
14        46   0.28   9.92          11.40     0.70
15        43   0.20   8.20           8.30     1.00
16        21   0.10   6.40           3.10     0.40
17        53   0.70   4.40          12.00     1.20
18        30   0.20   6.00           8.00     0.60
19        29   0.30   2.50           9.00     1.10
20        60   0.38  13.70          15.00     0.82
21        29   0.40   5.40           5.50     0.00
22        52   0.40  10.30          11.40     0.30
23        68   1.00   9.00          14.00     2.60
24        15   0.10   3.20           3.90     0.50
25        43   0.40   1.00          11.00     0.00
26        34   0.00   8.00           8.00     0.00
27        45   0.40   9.10           8.30     0.00
28        36   0.40   3.00           7.00     1.00
29        25   0.10   1.70           8.40     0.30
30        83   1.20  13.70          18.70     1.70
31        60   1.50   8.00           9.00     9.00
32        69   0.16  16.00          18.10     0.72
33        43   0.39   8.10           9.80     1.44
34        44   0.40   3.00           8.00     0.60
35       160  14.66   0.66           8.53     2.00
36        61   0.50   8.90          14.60     1.14
37        46   0.10   4.00          12.20     0.40
38        50   0.30   8.00          12.00     1.00
39        39   0.25   8.40           9.50     0.90
40        95   0.00  19.10          23.20     1.72
41        44   1.26   0.50           7.56     1.78

In [28]:
dados.to_json('arquivo_frutas.json')